version: "3"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./db_init:/docker-entrypoint-initdb.d"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    working_dir: /app
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - "./backend:/app"
    working_dir: /app
    command: ["npx", "nodemon", "index.js"]
    depends_on:
      - database

volumes:
  mysql_data: